# Generated by Django 4.2 on 2023-04-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_beneficiary_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiary',
        ),
    ]
