# Generated by Django 4.2 on 2023-04-13 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_transaction_beneficiary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('card_name', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='beneficiary',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_status',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='credit_card',
        ),
        migrations.RemoveField(
            model_name='walletuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='beneficiary',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.beneficiary'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='transaction',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='wallet.transaction'),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='walletuser',
            name='upload_image',
            field=models.ImageField(default=None, upload_to='user_photos/'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='wallet.account'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='walletuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.AddField(
            model_name='wallet',
            name='card',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='wallet.card'),
        ),
    ]
